[launcher]
author = brett.whynot@gmail.com
version = 1.0.4
description = Infoblox Grid Manager

[package]
id = TA-infoblox-gridmanager

[id]
name = TA-infoblox-gridmanager
version = 1.0.4

[ui]
label = Infoblox Grid Manager
is_visible = 0

