[infoblox_gridmanager]
sourcetype = infoblox:gridmanager
interval = 3600
python.version = python3
python.required = 3.9, 3.13
usessl = 1
verifyssl = 1
version = v2.10
limit = 1000
fields = network,extattrs,options